config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get '/my_bikes', to: 'bikes#my_bikes', as: :my_bikes

  devise_for :users
  resources :bikes do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:create]
  end
  resources :bookings, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  has_many :reviews, dependent: :destroy

  include PgSearch::Model

  pg_search_scope :supersearch,
   against: :location,
   using: {
     tsearch: { prefix: true }
   }

  include PgSearch::Model

  pg_search_scope :supersearch,
   against: :location,
   using: {
     tsearch: { prefix: true }
   }

  validates :description, presence: true
  validates :price, presence: true
  validates :location, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bike

  validates :pick_up, presence: true
  validates :drop_off, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :bike
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :bookings
  has_many :bikes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_counter
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def set_counter
    @bike_count = Bike.count
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_bike, only: [:show, :edit, :update, :destroy]
  def index
    if params[:query].present?
      @bikes = policy_scope(Bike).where("location ILIKE ?", "%#{params[:query]}%")
        @markers = @bikes.geocoded.map do |bike|
          {
            lat: bike.latitude,
            lng: bike.longitude,
            info_window: render_to_string(partial: "info_window", locals: { bike: bike }),
          }
        end
    else
      @bikes = policy_scope(Bike).order(created_at: :desc)
        @markers = @bikes.geocoded.map do |bike|
          {
            lat: bike.latitude,
            lng: bike.longitude,
            info_window: render_to_string(partial: "info_window", locals: { bike: bike }),
          }
        end
    end
    puts @markers
  end

  def new
    @bike = Bike.new
    authorize @bike
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user
    authorize @bike
    if @bike.save
      redirect_to bikes_path
    else
      render :new
    end
  end
  
  def show
    @booking = Booking.new
    @bike = Bike.find(params[:id])
    @review = Review.new 
  end

  def edit 
  end

  def update
    if @bike.update(bike_params)
    redirect_to bikes_path
    else
      render :edit
    end
  end

  def destroy
    if @bike.destroy
    redirect_to bikes_path(@bike)
    else
      render :index
    end
  end

  def my_bikes
    @my_bikes = current_user.bikes
    authorize @my_bikes

    @my_bookings = current_user.bookings
  end

  private
  def bike_params
    params.require(:bike).permit(:photo, :description, :price, :location)
  end

  def set_bike
    @bike = Bike.find(params[:id])
    authorize @bike
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :set_bike, only: [:new, :create]

  def show
    authorize @booking
    @bike = @booking.bike
  end

  def new
    @booking = Booking.new
  end

  def create
    @bike = Bike.find(params[:bike_id])
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.bike = @bike
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking)
    else
      redirect_to bike_path(@bike)
    end
  end

  def edit
    authorize @booking
  end

  def update
    authorize @booking
    if @booking.update(booking_params)
      redirect_to my_bikes_path
      else
        render :edit
      end
  end


  def destroy
    authorize @booking
    @booking.destroy
    redirect_to root_path
  end

  private
  def booking_params
    params.require(:booking).permit(:pick_up, :drop_off)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_bike
    @bike = Bike.find(params[:bike_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    if params[:query].present?
      redirect_to bikes_path(query: params[:query])
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @bike = Bike.find(params[:bike_id])
    @review = Review.new(review_params)
    @review.bike = @bike
    authorize @review
    if @review.save
      redirect_to bike_path(@bike, anchor: "review-#{@review.id}")
    else
      render 'bikes/show'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    authorize @review
    redirect_to bike_path(@review.bike.id)
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_card.html.erb
<div class="card-product">
<%= cl_image_tag @bike.photo.key, height: 300, width: 400, crop: :fill %>
  <div class="card-product-infos">
    <h2><%= @bike.description %></h2>
    <p>€  <%= @bike.price %></p>
    <p><%= @bike.location %></p>
  </div>
</div>

app/views/bikes/_card_booked.html.erb
<div class="card-product">
<%= cl_image_tag @bike.photo.key, height: 300, width: 400, crop: :fill %>
  <div class="card-product-infos">
    <h2>Your booking details</h2>

    <p class="mt-0"><small>Start Date | End date</small></p>
    <p class="mt-0"><small> <%= @booking.pick_up %> | <%= @booking.drop_off %></small></p>

    <hr>
    <p><strong>Pick up point | Drop off point</strong></p>
    <p><%= @bike.location %></p>

    <p>€  <%= @bike.price %> / per day</p>
    
  </div>
</div>

app/views/bikes/_form.html.erb
<%= simple_form_for(article) do |f| %>
  <!-- [...] -->
  <%= f.input :photo, as: :file %>
  <!-- [...] -->
<% end %>

app/views/bikes/_info_window.html.erb
<div class="window">
  <h2><%= bike.description %></h2>
  <p><%= bike.location %></p>
  <div class="text-right">
    <%= link_to 'Book', bike_path(bike) , class: 'btn btn-sm btn-primary'%>
  </div>
</div>

<style>
  .window {
    background-color: #ffffff !important;
    padding: 2% 11%;
    top: 0 !important;
    left: 0 !important;
    width: 100% !important;
    height: 100% !important;
    min-height: 120px !important;
    padding-top: 10px;
    display: block !important;
    color: #76cff0;
  }
  p {
    color: #76cff0;
    font-size: 16px;
    font-weight: 700;
    padding: 5px 0;
  }

  .mapboxgl-popup-close-button {
    background-color: #ffffff !important;
    margin: 0;
    padding: 0;
    top: 0;
    color: #76cff0;
    font-size: 16px;
  }
  .mapboxgl-popup-content {
    background-color: #ffffff !important;
    border-radius: 10px;
  }
  .window:hover {
  opacity: 0.5;
}
</style>

app/views/bikes/_new.html.erb
<div class="form-style">
  <%= simple_form_for @bike do |f| %> 
  <%= f.input :description, placeholder: "City Bike" %> 
  <%= f.input :photo, input_html: { class: 'd-none' }, label_html: { class: 'upload-photo'},
  label: '📷 Upload a photo' %>
  <%= f.input :price, placeholder: "€40" %>
  <%= f.input :location, placeholder: "Amsterdam" %>
  <div class="user-button mt-5">
    <%= f.submit class:'btn btn-primary btn-block'%> 
  </div>
  <% end %>
</div>

<style>
  .upload-photo {
    border: 1px solid #d3d3d3;
    padding: 16px 24px;
    cursor: pointer;
    font-weight: 500;
    background: white;
    border-radius: 5px;
  }
  .form-style{
    width: 800px;
  }

</style>

app/views/bikes/edit.html.erb
<%= render 'shared/banner_new' %>
<div class= "d-flex justify-content-center align-items-center">
  <div class="mt-5 mb-5 p-5 bg-white rounded d-flex shadow rounded">
  <%= render 'bikes/new', bike: @bike %>
  </div>
</div>

<style>
  .img-form{
    border-radius: 10px;
  }
</style>
  

app/views/bikes/index.html.erb
<div class="bikes-layout border-bottom border-top">
  <div>
    <h1 class="title-card" style="font-family: 'Castoro', serif">
      Find the <strong id="title-index">perfect bike</strong>
      <strong id="title-index">to enjoy</strong> the city
      <i class="fas fa-heart" style="font-size: 25px"></i>
    </h1>
    <div class="cards-position">
      <% @bikes.each do |bike| %>
      <div class="card-bike-container">
        <div class="card-bike" id="">
          <% if bike.photo.attached? %> <%= cl_image_tag bike.photo.key %> <%
          end %>
          <div class="card-content">
            <div class="card-description">
              <h5><strong><%= bike.description %></strong></h5>
              <h5 class="card-price">
                <strong>€<%= bike.price %> / per day</strong>
              </h5>
            </div>

            <p id="city"><%= bike.location %></p>
            <p>Contact: <%= bike.user.email %></p>
            <div class="user-button">
              <h5 class="card-title">
                <%= link_to 'Book', bike_path(bike), class:'btn btn-primary'%>
              </h5>
              <div class="user-button-actions">
                <% if policy(bike).edit? %> <%= link_to 'Edit',
                edit_bike_path(bike), class:'btn btn-primary' %> <% end %> <% if
                policy(bike).destroy? %> <%= link_to 'Delete', bike_path(bike),
                method: :delete, remote: true, data: { confirm: "Are you sure you want to
                delete this bike?"}, class: 'btn btn-danger' %> <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <div
    id="map"
    style="width: 50vw; height: calc(100vh - 80px)"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

app/views/bikes/my_bikes.html.erb
<div class="container">
  <h3 style="margin-top: 150px; font-family: 'Castoro', serif">
    Bikes I have posted for rent
  </h3>
  <div class="my-bikes-cards">
    <% @my_bikes.each do |bike| %>
      <div class="card-bike">
        <%= cl_image_tag bike.photo.key %>
        <div class="card-content">
          <div class="card-description">
            <h5><strong><%= bike.description %></strong></h5>
            <h5 class="card-price"><strong>€<%= bike.price %></strong></h5>
          </div>
          <% if bike.bookings.count == 0 %>
            <p>This bike hasn´t been booked yet</p>
            <div class="user-button">
              <div class="user-button-actions">
                <% if policy(bike).edit? %> <%= link_to 'Edit',
                edit_bike_path(bike), class:'btn btn-primary' %> <% end %> <% if
                policy(bike).destroy? %> <%= link_to 'Remove bike', bike_path(bike),
                method: :delete, remote: true, data: { confirm: "Are you sure you want to
                remove this bike?"}, class: 'btn btn-danger' %> <% end %>
              </div>
            </div>
          <% else %>
            <p><strong>This bike´s bookings:</strong></p>
            <% bike.bookings.each do |booking| %>
              <p>Pick up date: <%= booking.pick_up %> </p>
              <p>Drop off date: <%= booking.pick_up %> </p>
              <p>Contact: <%= booking.user.email %> </p>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <h3 style="margin-top: 50px; font-family: 'Castoro', serif">
    Bikes I have rented to use
  </h3>
  <div class="my-bikes-cards">
    <% @my_bookings.each do |booking| %>
      <div class="card-bike">
        <% if booking.bike.photo.attached? %> <%= cl_image_tag booking.bike.photo.key %> <%
        end %>
        <div class="card-content">
          <div class="card-description">
            <h5><strong><%= booking.bike.description %></strong></h5>
            <h5 class="card-price"><strong>€<%= booking.bike.price %></strong></h5>
          </div>

          <p id="city"><%= booking.bike.location %></p>
          <p>Contact: <%= booking.bike.user.email %></p>
          <p>Pick up date: <%= booking.pick_up %> </p>
          <p>Drop off date: <%= booking.drop_off %> </p>
          <p>Contact: <%= booking.user.email %> </p>
          <div class="user-button">
            <div class="user-button-actions">
              <% if policy(booking).edit? %> <%= link_to 'Edit',
              edit_booking_path(booking), class:'btn btn-primary' %> <% end %> <% if
              policy(booking).destroy? %> <%= link_to 'Cancel', booking_path(booking),
              method: :delete, remote: true, data: { confirm: "Are you sure you want to
              cancel this booking?"}, class: 'btn btn-danger' %> <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
 
</div>

app/views/bikes/new.html.erb
<%= render 'shared/banner_new' %>
<div class= "d-flex justify-content-center align-items-center">
  <div class="mt-5 mb-5 p-5 bg-white rounded d-flex shadow rounded">
  <%= render 'bikes/new', bike: @bike %>
  </div>
</div>

<style>
  .img-form{
    border-radius: 10px;
  }
</style>

app/views/bikes/show.html.erb
<%= render 'shared/banner' %>

<div class="pt-5 pb-5 px-5">
  <div class="d-flex justify-content-between booking-content">
  <div class="booking-info container-listing">
    <%= render 'bikes/card' %>
    <%= pluralize @bike.reviews.size, "review" %>
    </div>
    <div class="booking-form d-flex align-items-center justify-content-center">
    <div>
      <%= simple_form_for [@bike, @booking] do |form| %>
       <%= form.input :pick_up
      %> <%= form.input :drop_off %>
      <div class="user-button">
        <%= form.submit class:'btn btn-primary' %>
        <% end %> 
        <%= link_to "Cancel", bikes_path, class:'btn btn-primary user-button-actions' %>
      </div>
    </div>
    </div>
  </div>

  <div id="reviews">
    <% if @bike.reviews.blank? %>
      <div class="reviews-title">
        <strong>Be the first to leave a review for <%= @bike.description %></strong>
      </div>
    <% else %>
    <div class="reviews-title">
      <strong>Bike´s reviews</strong>
    </div>
      <div>
        <% @bike.reviews.each do |review| %>
          <div class="review card-product d-flex justify-content-between flex-column" >
            <p id="review-<%= review.id %>" style="font-size: 20px; padding-top:10px"><%= review.content %></p>
          </div> 
        <% end %>
      </div>
    <% end %>
  </div class="reviews-form">
  <%= simple_form_for([ @bike, @review ], remote: true) do |f| %>
    <%= f.input :content, as: :text, label:"Write a review", style: "font-size:20px", input_html: {rows: 5} %>
    <%= f.button :submit, class:'btn btn-primary' %>
  <% end %>
</div>

app/views/bookings/_form.html.erb
<div class="form-style">
  <%= simple_form_for booking do |f| %> 
  <%= f.input :pick_up %> 
  <%= f.input :drop_off %> 
  <div class="user-button mt-5">
    <%= f.submit class:'btn btn-primary btn-block'%> 
  </div>
  <% end %>
</div>

app/views/bookings/edit.html.erb
<div class= "d-flex justify-content-center align-items-center">
  <div class="mt-5 mb-5 p-5 bg-white rounded d-flex shadow rounded">
  <%= render 'form', booking: @booking %>
  </div>
</div>
  

app/views/bookings/show.html.erb
<%= render 'shared/banner_booked' %>

<div class="d-flex">
  <div class= "mt-5 mb-5">
    <%= render 'bikes/card_booked' %>
  </div>
  <img src="https://media.giphy.com/media/12UlfHpF05ielO/giphy.gif" class="rounded mx-auto booking-img mt-5 mb-5">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BikesAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
    </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
  
    <%= yield %>
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
        <div class="banner" style="background-image:url(https://images.unsplash.com/photo-1474552226712-ac0f0961a954?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1502&q=80); background-size:cover; padding-top:100px; background-position:70% 65%; heigth:800px">
					<form class="container  rounded" style=" margin-left: 5px; max-width: 620px; padding: 0 30px 60px 30px; font-family: Helvetica; font-weight: 600; color: #eceaea;">
						<h1 style="font-size: 4em; font-weight: bold; margin-bottom: 15px; margin-left:4mm;">Book the bike of your dreams.</h1>
						
						<div class="container">
						  <%= form_tag bikes_path, method: :get do %>
								<label>LOCATION</label>
								<%= text_field_tag :query,
									params[:query],
									class: "form-control",
									placeholder: "Where do you need a bike?" %>
										<div class="label">
											<label for="pick-up">PICK-UP</label>
										</div>
									<div>
										<input type="date" id="pick-up" name="pick-up"
										value="2021-07-02"
										 min="2021-07-02"
										 class="p-1">
									</div>
                  <div class="label">
										<label for="drop-off">DROP-OFF</label>
									</div>
									<div>
										<input type="date" id="drop-off" name="drop-off"
										value="2021-07-02"
										min="2021-07-02"
										class="p-1">
									</div>
									<div class="button">
										<%= submit_tag "Find a Bike", class: "btn btn-primary" %>
									</div>
							<% end %>
						</div>
	
						
        </div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1531923610693-c816870f3b44?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80);">
  <div class="container">
    <h1>Are you ready for your <strong>next experience</strong> with <strong>Bikes Airbnb?</strong></h1>
    <p>Just one more step ahead to finish your booking!</p>
  </div>
</div>

app/views/shared/_banner_booked.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1598649680252-bc67e10f975d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80);">
  <div class="container">
    <h1><strong>Congratulations!</strong> Your <strong>booking for <strong>"<%= @bike.description %>"</strong> 
has been confirmed!</strong></h1>
    <p>See bellow your booking information.</p>
  </div>
</div>

app/views/shared/_banner_new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1447871852826-1c11ef907903?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1051&q=80);">
  <div class="container">
    <h1>Post your bike at <strong>Bikes Airbnb!</strong></h1>
    <p>Create more life experiences by allowing people from anywhere to use your bike to run the world!</p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer border-top">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Bikes Airbnb <i class="fas fa-heart"></i> cares for you
  </div>
</div>

app/views/shared/_home_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-home">
  <div>
  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "navbarlogo.png", alt: "", width: "300px" %>
    <% end %>
    </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link text-white" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link text-white"  %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-home">
  <a class="navbar-brand" href="/">
    <%= image_tag "logo.png", alt: "alttext", class: "logo" %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
          <%= link_to "Rent your bike", new_bike_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "See All Bikes", bikes_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown ml-3">
          <%= image_tag "https://images.unsplash.com/photo-1584999734482-0361aecad844?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Bikes", my_bikes_path, class: "dropdown-item" %>
            <%= link_to "My Bookings", new_bike_path, class: "dropdown-item" %>
            <%= link_to "Edit Account", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>